import { Dimensions } from "react-native";

const FULL_SIZE = "100%";
const FULL_WINDOW_WIDTH = Dimensions.get("window").width;
const FULL_WINDOW_HEIGHT = Dimensions.get("window").height;
const COMMON_HEADER_OPTIONS_CONFIG = {
  headerShown: false,
};

const COMMON_TAB_OPTIONS_CONFIG = {
  headerShown: false,
  tabBarStyle: { display: "none" },
};
const SCREENS = {
  AUTH: "Auth" as never,
  LOGIN: "Login" as never,
  MAIN: "Main" as never,
  NAV_BAR: "NavBar" as never,
  CONTROL: "Control" as never,
  CANVAS: "Canvas" as never,
  MANUAL: "Manual" as never,
  PATTERN: "Pattern" as never,
  CREATE_PATTERN: "CreatePattern" as never,
  DISPLAY_PATTERN: "DisplayPattern" as never,
  SAVE_PATTERN: "SavePattern" as never,
  NEW_PATTERN: "NewPattern" as never,
  KINK: "Kink" as never,
  KINK_HUB: "KinkHub" as never,
  KINK_SELECTION: "Kink Selection" as never,
  KINK_INTRO: "Kink Introduction" as never,
  KINK_EMOTIONSELECTION: "Kink Emotion Selection Screen" as never,
  KINK_INTENSITY_SELECTION: "Kink Intensity Selection Screen" as never,
  KINK_SENSITIVITY_SELECTION: "Kink Sensitivity Selection Screen" as never,
  KINK_FUNTYPE: "Kink Fun Tyle Selection Screen" as never,
  KINK_SAVE: "Kink Save Screen" as never,
  KINK_WAITING: "Kink Waiting Screen" as never,
  KINK_CONFIRMATION: "Kink Confirmation Screen" as never,
  KINK_PLAY: "Kink Play Screen" as never,
  ACCOUNTS: "Accounts" as never,
  PLAYGROUND_STACK: "Playground Stack" as never,
  PLAYGROUND: "Playground" as never,
  REGISTER: "Register" as never,
  REGISTER_PASSWORD: "Register Password" as never,
  REGISTER_PROFILE_PIC_NICKNAME: "Register Profile Pic Nickname" as never,
  REGISTER_BIO: "Register Bio" as never,
  REGISTER_SKIP_BIO: "Skip Bio" as never,
  REGISTER_PROFILE: "Register Profile" as never,
  REGISTER_SKIP_PROFILE: "Skip Profile" as never,
  REGISTER_VERIFY_CODE: "Register Verify Code" as never,
  EMAIL_VERIFIED: "Email Verified" as never,
  REGISTER_DONE: "Register Done" as never,
  FORGOT_PASSWORD: "Forgot Password" as never,
  VERIFY_CODE: "Verify Code" as never,
  UPDATE_PASSWORD: "Update Password" as never,
  PASSWORD_SET: "Password Set" as never,
  PROFILE: "Profile" as never,
  PROFILEMAIN: "ProfileMain" as never,
  PROFILE_DEVICE_TRAINING: "ProfileDeviceTraining" as never,
  PROFILE_SETTING_ACCOUNT: "ProfileSettingAccount" as never,
  PROFILE_SETTING_ACCOUNT_MAIN: "ProfileSettingAccount Main" as never,
  PROFILE_SETTING_ACCOUNT_RESET_PASSWORD_STACK:
    "ProfileSettingAccount Reset Password Stack" as never,
  PROFILE_SETTING_ACCOUNT_RESET_PASSWORD_EMAIL_VERIFICATION:
    "ProfileSettingAccount Reset Password Email Verification" as never,
  PROFILE_SETTING_ACCOUNT_RESET_PASSWORD:
    "ProfileSettingAccount Reset Password" as never,
  PROFILE_SETTING_ACCOUNT_RESET_PASSWORD_SUCCESS:
    "ProfileSettingAccount Reset Password Success" as never,
  PROFILE_SETTING_ACCOUNT_RESET_EMAIL_STACK:
    "ProfileSettingAccount Reset Email Stack" as never,
  PROFILE_SETTING_ACCOUNT_RESET_EMAIL:
    "ProfileSettingAccount Reset Password" as never,
  PROFILE_SETTING_ACCOUNT_RESET_EMAIL_VERIFICATION:
    "ProfileSettingAccount Reset Email Verification" as never,
  PROFILE_SETTING_ACCOUNT_RESET_EMAIL_SUCCESS:
    "ProfileSettingAccount Reset Email Success" as never,
  PROFILE_SETTING_LANGUAGE: "ProfileSettingLanguage" as never,
  PROFILE_SETTING_ABOUTUS: "ProfileSettingAboutUs" as never,
  PROFILE_SETTING_HELP: "ProfileSettingHelp" as never,
  PROFILE_SETTING_PRIVACY: "ProfileSettingPrivacy" as never,
  PROFILE_EDIT: "ProfileEdit" as never,
  ONBOARDING: "Onboarding" as never,
  ONBOARDING_STEP1: "OnBoardingStep1" as never,
  ONBOARDING_STEP2: "OnBoardingStep2" as never,
  ONBOARDING_STEP3: "OnBoardingStep3" as never,
  ONBOARDING_STEP4: "OnBoardingStep4" as never,
  ONBOARDING_STEP5: "OnBoardingStep5" as never,
  ONBOARDING_STEP6: "OnBoardingStep6" as never,
  ONBOARDING_STEP7: "OnBoardingStep7" as never,
  ONBOARDING_TEST: "OnboardingTest" as never,
  CONNECT_DEVICE: "ConnectDevice" as never,
  HOME: "Home" as never,
  ALARM_STACK: "Alarm Stack" as never,
  SETALARM_INTRO: "Set Alarm Introduction" as never,
  SETALARM_TIME: "Set Alarm Time" as never,
  SETALARM_PATTERN: "Set Alarm Pattern" as never,
  SETALARM_LIST: "Set Alarm List" as never,
  HOMEMAIN: "HomeMain" as never,
  MESSAGE_MAINTENANCE_PAGE: "MessageMaintenancePage" as never,
  CHAT: "Chat" as never,
  CHAT_THREAD: "ChatThread" as never,
  CHAT_SEARCH: "ChatSearch" as never,
  CHAT_SETTINGS: "ChatSettings" as never,
  CHAT_CREATE: "ChatCreate" as never,
  CHAT_CONTACT: "ChatContact" as never,
  CHAT_CALL: "ChatCall" as never,
  SYNC_STACK: "SyncStack" as never,
  MESSAGETAB: "MessageTab" as never,
  MAINAPPTAB: "MainAppTab" as never,
  MOTION_STACK: "MotionStack" as never,
  MOTION_SENSOR: "Motion Sensor" as never,
  MOTION_INTRODUCTION: "Motion Introduction" as never,
  QUICK_BLISS_SLIDER: "Quick Bliss Slider" as never,
  BLISS_TIMER: "Bliss Timer" as never,
  BLISS_STACK: "Bliss Stack" as never,
  DEEP_DISCOVERY_STACK: "Deep Discovery Stack" as never,
  DEEP_DISCOVERY_SLIDER: "Deep Discovery Slider" as never,
  DEEP_DISCOVERY_TIMER: "Deep Discovery  Timer" as never,
  SYNC_SELECTION_SCREEN: "Sync Selection Screen" as never,
  SYNC_INTRODUCTION: "Sync Introduction " as never,
  SYNC_SCREEN: "Sync Screen" as never,
  SOUND: "Sound" as never,
  SOUND_METER: "Sound Meter" as never,
  SOUND_INTRO: "Sound Introduction" as never,
  AVATAR_STACK: "AvatarStack" as never,
  AVATAR_IDENTITY: "AvatarIdentity" as never,
  AVATAR_READY: "AvatarReady" as never,
  AVATAR_APPEARANCE: "AvatarAppearance" as never,
  AVATAR_CUSTOMIZE: "AvatarCustomize" as never,
  AVATAR_PERSONALITY: "AvatarPersonality" as never,
  AVATAR_STORY: "AvatarStory" as never,
  AVATAR_INTIMATE: "AvatarIntimate" as never,
  AVATAR_CANDLE: "AvatarCandle" as never,
  AVATAR_WAITING: "AvatarWaiting" as never,
  LOVE_CHAT: "LoveChat" as never,
  LOVE_CALL: "LoveCall" as never,
  LOVE_SYNC: "LoveSync" as never,
  OPEN_ANIMATION: "OpenAnimation" as never,
  PASSWORD_RESET_CONFIRM: "Password Reset Confirm" as never,
  USER_FEEDBACK: "UserFeedback" as never,
  PAIR_BAND_APP: "PairBandApp" as never,
  PAIR_BAND_POWER: "PairBandPower" as never,
  PAIR_TOY_POWER: "PairToyPower" as never,
  PAIR_TOY_MATCH: "PairToyMatch" as never,
  AUTO: "Auto" as never,
  PERFORMANCE: "Performance" as never,
  PERFORMANCE_PLAY: "PerformancePlay" as never,
  FEED: "Feed" as never,
  PREMIUM: "Premium" as never,
  TUTORIAL: "Tutorial" as never,
  SWITCH_ACCOUNTS: "SwitchAccounts" as never,
  PROFILE_LLM: "ProfileCompanionAi" as never,
} as const;

export {
  COMMON_HEADER_OPTIONS_CONFIG,
  COMMON_TAB_OPTIONS_CONFIG,
  FULL_SIZE,
  FULL_WINDOW_HEIGHT,
  FULL_WINDOW_WIDTH,
  SCREENS,
};
